#ifndef __mainframe__
#define __mainframe__

/**
@file
Subclass of G_MainFrame, which is generated by wxFormBuilder.
@todo Add your event handlers directly to this file.
*/

#include "gui.h"

/** Implementing G_MainFrame */
class MainFrame : public G_MainFrame
{
public:
	/** Constructor */
	MainFrame( wxWindow* parent );
};

#endif // __mainframe__
