#ifndef __prefs__
#define __prefs__

/**
@file
Subclass of _PrefsDialog, which is generated by wxFormBuilder.
*/

#include "prefsdialog.h"
#include <wx/imaglist.h>
//// end generated include

/** Implementing _PrefsDialog */
class PrefsDialog : public _PrefsDialog
{
	public:
		/** Constructor */
		PrefsDialog( wxWindow* parent );
	//// end generated class members
		void OnClose( wxCommandEvent& event );
		void OnToggleLocale( wxCommandEvent& event );

		void PrefsDialogSetup();

private:
	wxImageList* imgList;
};

#endif // __prefs__
