CXX = g++

LIBCOMMON = libcommon.dll
LIBLAYOUT = liblayout.dll


LDFLAGS = -L. -LC:/wx-2.4.2_compiled_as_dll/lib -mthreads -mwindows
EXTRALIBS =  -mthreads -lrpcrt4 -loleaut32 -lole32 -luuid -lodbc32 -lole32 -loleaut32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lcomdlg32 -lctl3d32 -ladvapi32 -lwsock32 -lgdi32

DEBUG = -g
CXXFLAGS = -DWINVER=0x0400 -D__WIN95__ -D__GNUWIN32__ -D__WIN32__ -DHAVE_W32API_H  -D__WXMSW__ -D__WINDOWS__ -Wall -fno-pcc-struct-return -O2 -Os -D__WXFB_DEBUG__ -D__WX24__ -DWXUSINGDLL -IC:/wx-2.4.2_compiled_as_dll/include $(DEBUG)
LIBS = -mthreads -Wl,--subsystem,windows -mwindows -lwxmsw242 -lpng -ljpeg -lregex -ltiff -lzlib -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lole32 -loleaut32 -luuid -lrpcrt4 -ladvapi32 -lwsock32 -lodbc32

all: $(LIBCOMMON) $(LIBLAYOUT)

$(LIBCOMMON): common.o
	$(CXX) -L. -shared -o $(LIBCOMMON) common.o -lstdc++ $(LDFLAGS)  $(LIBS)
	strip $(LIBCOMMON)

common.o: common.cpp
	$(CXX) -c $(CXXFLAGS) -o common.o common.cpp

$(LIBLAYOUT): layout.o
	$(CXX) -L. -shared -o $(LIBLAYOUT) layout.o -lstdc++ $(LDFLAGS)  $(LIBS)
	strip $(LIBLAYOUT)

layout.o: layout.cpp
	$(CXX) -c $(CXXFLAGS) -o layout.o layout.cpp

