#ifndef __INDUSTRIAL_CONTROLS_DEF_
#define __INDUSTRIAL_CONTROLS_DEF_

#ifdef WXMAKINGDLL_INDCTRLS
#    define WXDLLIMPEXP_INDCTRLS WXEXPORT
#elif defined(WXUSINGDLL_INDCTRLS)
#    define WXDLLIMPEXP_INDCTRLS WXIMPORT
#else /* not making nor using as DLL */
#    define WXDLLIMPEXP_INDCTRLS
#endif // WXMAKINGDLL_INDCTRLS

#endif //__INDUSTRIAL_CONTROLS_DEF_
