matrix:
  IMAGE:
    - ubuntu:16.04
pipeline:
  build:
    image: ${IMAGE}
    commands:
      - apt update
      - apt install -y dpkg-dev debhelper libwxgtk3.0-dev libwxgtk-media3.0-dev libboost-dev
      - cp -R install/linux/debian .
      - dpkg-buildpackage -rfakeroot -us -uc
      - mkdir -p output/${IMAGE}
      - mv ../*.deb output/${IMAGE}
