version: 1.0.{build}
environment:
  MSYSTEM: MINGW32
install:
- cmd: >-
    cinst -y InnoSetup

    C:\msys64\usr\bin\bash -lc "pacman -S --needed --noconfirm mingw-w64-i686-wxWidgets"
build_script:
- cmd: >-
    git submodule update --init


    create_build_files4.bat --wx-root=/mingw32/bin --force-wx-config --disable-mediactrl


    C:\msys64\usr\bin\bash -lc "ln -s /mingw32/include/binutils/bfd.h /mingw32/include/bfd.h"

    C:\msys64\usr\bin\bash -lc "ln -s /mingw32/include/binutils/symcat.h /mingw32/include/symcat.h"

    C:\msys64\usr\bin\bash -lc "ln -s /mingw32/lib/binutils/libbfd.a /mingw32/lib/libbfd.a"

    C:\msys64\usr\bin\bash -lc "ln -s /mingw32/lib/binutils/libiberty.a /mingw32/lib/libiberty.a"


    C:\msys64\usr\bin\bash -lc "cd '%cd%'/build/3.0/gmake && sed 's!\$(LDFLAGS) \$(RESOURCES) \$(ARCH) \$(LIBS)!\$(LIBS) \$(LDFLAGS) \$(RESOURCES) \$(ARCH)!g' *.make -i"

    C:\msys64\usr\bin\bash -lc "cd '%cd%'/build/3.0/gmake && sed 's!-lbfd!-lbfd -lz!g' *.make -i"


    C:\msys64\usr\bin\bash -lc "cd '%cd%'/build/3.0/gmake && make config=release"
