version: 1.0.{build}
environment:
  MSYSTEM: MINGW32
install:
- cmd: >-
    cinst -y InnoSetup

    C:\msys64\usr\bin\bash -lc "pacman -S --needed --noconfirm mingw-w64-i686-wxWidgets mingw-w64-i686-boost"
build_script:
- cmd: >-
    git submodule update --init


    create_build_files4.bat --wx-root=/mingw32/bin --force-wx-config --disable-mediactrl


    C:\msys64\usr\bin\bash -lc "ln -s /mingw32/include/binutils/bfd.h /mingw32/include/bfd.h"

    C:\msys64\usr\bin\bash -lc "ln -s /mingw32/include/binutils/symcat.h /mingw32/include/symcat.h"

    C:\msys64\usr\bin\bash -lc "ln -s /mingw32/lib/binutils/libbfd.a /mingw32/lib/libbfd.a"

    C:\msys64\usr\bin\bash -lc "ln -s /mingw32/lib/binutils/libiberty.a /mingw32/lib/libiberty.a"


    C:\msys64\usr\bin\bash -lc "cd '%cd%'/build/3.0/gmake && sed 's!\$(LDFLAGS) \$(RESOURCES) \$(ARCH) \$(LIBS)!\$(LIBS) \$(LDFLAGS) \$(RESOURCES) \$(ARCH)!g' *.make -i"

    C:\msys64\usr\bin\bash -lc "cd '%cd%'/build/3.0/gmake && sed 's!-lbfd!-lbfd -lz!g' *.make -i"


    C:\msys64\usr\bin\bash -lc "cd '%cd%'/build/3.0/gmake && make config=release"

    7z a -r wxFormBuilder_win32.zip %cd%\output\*.* C:\msys64\mingw32\bin\wx*.dll C:\msys64\mingw32\bin\libstdc++*.dll C:\msys64\mingw32\bin\libgcc*.dll C:\msys64\mingw32\bin\libintl*.dll C:\msys64\mingw32\bin\libexpat*.dll C:\msys64\mingw32\bin\libjpeg*.dll C:\msys64\mingw32\bin\libpng*.dll C:\msys64\mingw32\bin\libtiff*.dll C:\msys64\mingw32\bin\zlib*.dll C:\msys64\mingw32\bin\libwinpthread*.dll C:\msys64\mingw32\bin\libiconv*.dll C:\msys64\mingw32\bin\liblzma*.dll

    appveyor PushArtifact wxFormBuilder_win32.zip


    cd install/windows

    create_source_package.bat

    "C:\Program Files (x86)\Inno Setup 5\ISCC.exe" wxFormBuilder.iss
artifacts:
- path: install\windows\wxFormBuilder*.exe
